#!/usr/bin/python3
# -*- coding: utf-8 -*

···7) Dadas dos listas, debes generar una tercera con todos los elementos que se repitan en ellas, pero no debe repetise ningún elemento en la nueva lista:"""

lista1=[]
lista2=[]
lista3=[]
for i in range(0,11,1):
    lista1.append(i)
for i in range(0,22,2):
    lista2.append(i)
print(lista1)
print(lista2)
for x in lista1: #recorremos los elements de l1
    if x in lista2: # averiguamos si x ques elemento d lista1 esta en l2
        lista3.append(x)
print(lista3)
