#!/usr/bin/python3 
# -*- coding: utf-8 -*-

try:
    lista = [1, 2, 3, 4, 5]
    lista[10]
except IndexError:
    print("En la lista no hay 10 posiciones, puedes saber la longitud con (len)")
print("Fin programa")
