#!/usr/bin/python3
# -*- coding: utf-8 -*-

#generador passw

import random
import string

def CreatePassw(name):
    print("Hola ", name," Selecciona como quieres la contraseña :")
    ok=False
    
    while not ok:
             
        print("Opción-1. Solo números?        .1")
        print("Opción-2. Solo letras?         .2")
        print("Opción-3. Símbolos, signos...? .3")
        print("Opcion-4. Mixed                .4")
        print("Other-  . Exit                 . ")
        
        x=input("Elige una opcion : ")
        if not x.isdigit():#comprobamos que sea un numero
            print("ErroR pedimos un número/opción :")
            break
        
        if x < "1" or x > "4":
            print("No Option, ",x," Exit, Ciao, Dew")
            break
            
        num_caracteres=input("De cuantos caracteres quieres la contraseña : ")
        if not num_caracteres.isdigit():#comprobamos que sea un numero sn break
            print("ErroR pedimos un número de caracteres en número")
            break
        caracters=int(num_caracteres)
        
        if x == "1":#creación password numerico
            print("Su password es : ")
            for i in range(caracters):
                pnum = random.randint(0, 9)
                print(pnum, end=''),
                
        elif x == "2":#creación password letras
            print("Su password es : ")
            for i in range(caracters):
                pnum = random.choice(string.ascii_letters)#seleccionamos entre las letras mayus y minis en ascii
                print(pnum, end=''),
            
        elif x == "3":#creación password símbolos y signos
            print("Su password es : ")
            for i in range(caracters):
                pnum = random.choice(string.punctuation)#seleccionamos entre l0s simbolos i signos
                print(pnum, end=''),
                
        elif x == "4":#creación password mixed
            print("Su password es : 3")
            for i in range(caracters):
                pnum = random.choice(string.ascii_letters + string.punctuation + string.digits)#seleccionamos entre todo                print(pnum, end=''),
                print(pnum, end='')
        
        ok=True
    
