#!/usr/bin/python3 
# -*- coding: utf-8 -*-

try:
    
    colores = { 'rojo':'red', 'verde':'green', 'negro':'black' } 
    colores['blanco']
except KeyError:
    print("Error: Color no incluido en lista ")
print("Fin programa")
