#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""1) Realiza un programa que lea dos números por teclado y permita elegir entre 3 opciones en un menú:
Mostrar una suma de los dos números Mostrar una resta de los dos números (el primero menos el segundo) Mostrar una multiplicación de los dos números En caso de no introducir una opción válida, el programa informará de que no es correcta."""

a = input("Introduce el 1er numero : ")
b = input("Introduce el 2do numero : ")

if a.isdigit()==False or b.isdigit()==False:
    print(" No habiamos dicho numeros ? ")
    
elif a.isdigit()==True or b.isdigit()==True:
    a=int(a)  #pasamos str a int
    b=int(b)
    print(a*b)
